# Generated by Django 3.0.3 on 2020-03-03 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LabCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labcycles', to='labs.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveLabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activelabs', to='instructors.Instructor')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activelabs', to='labs.Lab')),
                ('students', models.ManyToManyField(related_name='activelabs', to='students.Student')),
            ],
        ),
    ]
