# Generated by Django 3.0.3 on 2020-03-06 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        ('students', '0002_auto_20200303_1604'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activelabs', to='instructors.Instructor')),
                ('students', models.ManyToManyField(related_name='activelabs', to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveLabCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labcycles', to='labs.ActiveLab')),
            ],
        ),
        migrations.DeleteModel(
            name='ActiveLabs',
        ),
    ]
