# Generated by Django 3.0.3 on 2020-03-08 10:42

from django.db import migrations, models
import django.db.models.deletion
import labs.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200303_1604'),
        ('labs', '0002_auto_20200306_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FileField(blank=True, storage=labs.models.OverwriteStorage(), upload_to=labs.models.student_director_path)),
                ('labcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.ActiveLabCycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.AddField(
            model_name='activelabcycle',
            name='students',
            field=models.ManyToManyField(through='labs.Solution', to='students.Student'),
        ),
    ]
